In [3]:
import numpy as np
import pandas as pd
V1=np.array([1,3,12,32,24,3])
V2=np.array([3,4,2,12,2,24])
V3=np.array([4,1,12,2,42,3])
df=pd.DataFrame({"V1":V1,"V2":V2,"V3":V3}) #unutma böyle bir işlemi yani liste halinde yazmayı ("v1":V1i ) süslü parantezle yaparsın
df=df.astype(float) #ondalıklıya çevirme işlemi  12.0   normalde 12 dir
df

V1    V2    V3
0   1.0   3.0   4.0
1   3.0   4.0   1.0
2  12.0   2.0  12.0
3  32.0  12.0   2.0
4  24.0   2.0  42.0
5   3.0  24.0   3.0

In [4]:
 #değişkenin yapısı bozulmaz ama belli standartlara oturtturulur  yani bi 10 değeri 80.sırada olsun 
    #bu standartlaştırıldığında 2 3 gibi bir sıraya girmiş olur  1 2 3 gibi değer oluacak  ama özütü aynı olur yayılımı dağılım aynı
    # mod medyan falan değişir   ,  değişken dönüşümü ise  direkt özütünün kaybedilmesi cinsiyet dönüşümü 0 1 den yapı dğeişir


In [5]:
from sklearn import preprocessing 

In [6]:
preprocessing.scale(df)  #tüm değişkenleri standartlaştırmış oldu  tüm hepsi aynı oranda değiştiği için birbirleri arasındaki
#yapı değişmedi  bu Standardizasyon islemidir

array([[-0.98042624, -0.60351217, -0.46089801],
       [-0.80991733, -0.47864758, -0.66830212],
       [-0.04262723, -0.72837676,  0.0921796 ],
       [ 1.66246189,  0.52026911, -0.59916742],
       [ 0.98042624, -0.72837676,  2.16622066],
       [-0.80991733,  2.01864415, -0.53003271]])

In [7]:
#şimdi normalizasyon işlemine geçeceğiz 0 ile 1 arasına dönüştürmek için kullanılır
preprocessing.normalize(df) 

array([[0.19611614, 0.58834841, 0.78446454],
       [0.58834841, 0.78446454, 0.19611614],
       [0.70224688, 0.11704115, 0.70224688],
       [0.93472998, 0.35052374, 0.05842062],
       [0.49571543, 0.04130962, 0.867502  ],
       [0.12309149, 0.98473193, 0.12309149]])

In [9]:
#bu da istedğimiz değerler arasında dönüştürmeye yarar min max yani 
sclr=preprocessing.MinMaxScaler(feature_range=(10,20)) #dönüştürücü nesnesi oluşturdurk
sclr.fit_transform(df)

array([[10.        , 10.45454545, 10.73170732],
       [10.64516129, 10.90909091, 10.        ],
       [13.5483871 , 10.        , 12.68292683],
       [20.        , 14.54545455, 10.24390244],
       [17.41935484, 10.        , 20.        ],
       [10.64516129, 20.        , 10.48780488]])